### ISSUE TITLE
Menyfel

### ISSUE THREAD

**Issue by davidsomdal** [ZephyrAlex/GladRags#8]
För att reproducera felet:
Skala ner sidan i mobilt läge 
Öppna menyn
Skala upp sidan

Efter att ha gjort följande saknas meny knapparna.

**Comment by Amanthas** [comment]
Lösningen var att först lägga till en media query för storskärm, sedan
under den lägga till:

#menu_ul{
display: block !important;
}

Detta ser till så att "display: block" alltid skriver över "display
none" efter en viss bredd. Samma kodsnutt blev tilllagd i media queryn
för plattan för att menyn ska synas där med.
